"use client"
import './globals.css'
import type { Metadata } from 'next'
import { Inter , Poppins} from 'next/font/google'
import React from 'react'

import { QueryClient, QueryClientProvider, useQuery } from 'react-query'

const queryClient = new QueryClient()

const poppins = Poppins({ subsets: ['latin'] , weight : ['100' , '200' , '300' , '400' , '500' , '600' , '700']})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='bg-gradient-to-bl from-black to-gray-950 -z-50'>
       <QueryClientProvider client={queryClient}>
      <body className={poppins.className}>{children}</body>
      </QueryClientProvider>
    </html>
  )
}
